version: '3.8'

services:
  hometown:
    build: .
    container_name: hometown-analytics
    ports:
      - "8888:8888"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./notebooks:/app/notebooks
      - ./src:/app/src
    environment:
      - PYTHONPATH=/app/src
      - JUPYTER_ENABLE_LAB=yes
    restart: unless-stopped
    
  # Serviço para testes
  hometown-test:
    build: .
    container_name: hometown-test
    volumes:
      - ./:/app
    environment:
      - PYTHONPATH=/app/src
    command: poetry run pytest tests/ -v
    profiles:
      - test